//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBase
    {
        public int CustomerID { get; set; }
        public string Tel { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public string PostNumber { get; set; }
        public string Fax { get; set; }
        public Nullable<byte> SendInterFace { get; set; }
        public string Bak { get; set; }
        public string WasteBook { get; set; }
        public Nullable<int> BargainID { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> SendintFlag { get; set; }
        public Nullable<int> FetionFriendStatus { get; set; }
        public string Appsecret { get; set; }
        public string FetionUID { get; set; }
    }
}
